In [1]:
X = [
    "네, 안녕하세요. 반갑습니다.",
    "질문이나 건의사항은 깃헙 이슈 트래커에 남겨주세요.",
    "오류보고는 실행환경, 에러메세지와함께 설명을 최대한상세히!^^"
]
len(X)

3

In [2]:
import konlpy
mecab = konlpy.tag.Mecab('c:/mecab/mecab-ko-dic')

def tokenizer(s):
#    r = mecab.morphs(s)
    r = mecab.nouns(s)
    return r

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(tokenizer=tokenizer)
vectorizer.fit(X)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=<function tokenizer at 0x000001C86A5BD948>,
                vocabulary=None)

In [4]:
vectorizer.vocabulary_

{'네': 7,
 ',': 1,
 '안녕': 18,
 '하': 32,
 '세요': 15,
 '.': 2,
 '반갑': 10,
 '습니다': 16,
 '질문': 29,
 '이나': 26,
 '건': 4,
 '의': 25,
 '사항': 12,
 '은': 23,
 '깃': 5,
 '헙': 34,
 '이슈': 27,
 '트래커': 31,
 '에': 19,
 '남겨': 6,
 '주': 28,
 '오류': 21,
 '보고': 11,
 '는': 8,
 '실행': 17,
 '환경': 35,
 '에러': 20,
 '메세지': 9,
 '와': 22,
 '함께': 33,
 '설명': 14,
 '을': 24,
 '최대한': 30,
 '상세히': 13,
 '!': 0,
 '^^': 3}

In [5]:
X_bag_of_words = vectorizer.transform(X)
X_bag_of_words

<3x36 sparse matrix of type '<class 'numpy.int64'>'
	with 39 stored elements in Compressed Sparse Row format>

In [6]:
X_bag_of_words.toarray()

array([[0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0],
       [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
        1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [7]:
vectorizer.get_feature_names()

['!',
 ',',
 '.',
 '^^',
 '건',
 '깃',
 '남겨',
 '네',
 '는',
 '메세지',
 '반갑',
 '보고',
 '사항',
 '상세히',
 '설명',
 '세요',
 '습니다',
 '실행',
 '안녕',
 '에',
 '에러',
 '오류',
 '와',
 '은',
 '을',
 '의',
 '이나',
 '이슈',
 '주',
 '질문',
 '최대한',
 '트래커',
 '하',
 '함께',
 '헙',
 '환경']

In [8]:
vectorizer.inverse_transform(X_bag_of_words)

[array([',', '.', '네', '반갑', '세요', '습니다', '안녕', '하'], dtype='<U3'),
 array(['.', '건', '깃', '남겨', '사항', '세요', '에', '은', '의', '이나', '이슈', '주',
        '질문', '트래커', '헙'], dtype='<U3'),
 array(['!', ',', '^^', '는', '메세지', '보고', '상세히', '설명', '실행', '에러', '오류',
        '와', '을', '최대한', '함께', '환경'], dtype='<U3')]

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(tokenizer=tokenizer)
tfidf_vectorizer.fit(X)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=<function tokenizer at 0x000001C86A5BD948>,
                use_idf=True, vocabulary=None)

In [10]:
tfidf_vectorizer.transform(X).toarray()

array([[0.        , 0.26131363, 0.52262726, 0.        , 0.        ,
        0.        , 0.        , 0.34359602, 0.        , 0.        ,
        0.34359602, 0.        , 0.        , 0.        , 0.        ,
        0.26131363, 0.34359602, 0.        , 0.34359602, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.34359602, 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.20213029, 0.        , 0.26577704,
        0.26577704, 0.26577704, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.26577704, 0.        , 0.        ,
        0.20213029, 0.        , 0.        , 0.        , 0.26577704,
        0.        , 0.        , 0.        , 0.26577704, 0.        ,
        0.26577704, 0.26577704, 0.26577704, 0.26577704, 0.26577704,
        0.        , 0.26577704, 0.        , 0.        , 0.26577704,
        0.        ],
      

In [11]:
# look at sequences of tokens of minimum length 2 and maximum length 2
bigram_vectorizer = CountVectorizer(ngram_range=(2, 2), tokenizer=tokenizer)
bigram_vectorizer.fit(X)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(2, 2), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=<function tokenizer at 0x000001C86A5BD948>,
                vocabulary=None)

In [12]:
bigram_vectorizer.get_feature_names()

['! ^^',
 ', 안녕',
 ', 에러',
 '. 반갑',
 '건 의',
 '깃 헙',
 '남겨 주',
 '네 ,',
 '는 실행',
 '메세지 와',
 '반갑 습니다',
 '보고 는',
 '사항 은',
 '상세히 !',
 '설명 을',
 '세요 .',
 '습니다 .',
 '실행 환경',
 '안녕 하',
 '에 남겨',
 '에러 메세지',
 '오류 보고',
 '와 함께',
 '은 깃',
 '을 최대한',
 '의 사항',
 '이나 건',
 '이슈 트래커',
 '주 세요',
 '질문 이나',
 '최대한 상세히',
 '트래커 에',
 '하 세요',
 '함께 설명',
 '헙 이슈',
 '환경 ,']

In [13]:
bigram_vectorizer.transform(X).toarray()

array([[0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
        1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [14]:
gram_vectorizer = CountVectorizer(ngram_range=(1, 2), tokenizer=tokenizer)
gram_vectorizer.fit(X)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 2), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=<function tokenizer at 0x000001C86A5BD948>,
                vocabulary=None)

In [15]:
gram_vectorizer.get_feature_names()

['!',
 '! ^^',
 ',',
 ', 안녕',
 ', 에러',
 '.',
 '. 반갑',
 '^^',
 '건',
 '건 의',
 '깃',
 '깃 헙',
 '남겨',
 '남겨 주',
 '네',
 '네 ,',
 '는',
 '는 실행',
 '메세지',
 '메세지 와',
 '반갑',
 '반갑 습니다',
 '보고',
 '보고 는',
 '사항',
 '사항 은',
 '상세히',
 '상세히 !',
 '설명',
 '설명 을',
 '세요',
 '세요 .',
 '습니다',
 '습니다 .',
 '실행',
 '실행 환경',
 '안녕',
 '안녕 하',
 '에',
 '에 남겨',
 '에러',
 '에러 메세지',
 '오류',
 '오류 보고',
 '와',
 '와 함께',
 '은',
 '은 깃',
 '을',
 '을 최대한',
 '의',
 '의 사항',
 '이나',
 '이나 건',
 '이슈',
 '이슈 트래커',
 '주',
 '주 세요',
 '질문',
 '질문 이나',
 '최대한',
 '최대한 상세히',
 '트래커',
 '트래커 에',
 '하',
 '하 세요',
 '함께',
 '함께 설명',
 '헙',
 '헙 이슈',
 '환경',
 '환경 ,']

In [16]:
gram_vectorizer.transform(X).toarray()

array([[0, 0, 1, 1, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
        0, 0, 1, 1, 0, 0],
       [1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
        1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
        1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        1, 1, 0, 0, 1, 1]], dtype=int64)

In [17]:
gram_vectorizer.transform(['트래커 에러 안녕!']).toarray()

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0]], dtype=int64)

In [18]:
import numpy as np

np.dot(
    gram_vectorizer.transform(X).toarray(),
    gram_vectorizer.transform(['트래커 에러 안녕?']).toarray().T
)

array([[1],
       [1],
       [1]], dtype=int64)

In [19]:
import MeCab
tagger = MeCab.Tagger()
print(tagger.parse('트래커 에러 안녕?'))

트래커	NNP,*,F,트래커,*,*,*,*
에러	NNG,*,F,에러,*,*,*,*
안녕	IC,*,T,안녕,*,*,*,*
?	SF,*,*,*,*,*,*,*
EOS

